owner-repo: &owner-repo
  owner-repo: najork/health-sync-server

excutor: &executor
  executor:
    name: go/golang-docker
    go-docker-version: 1.16-java-11-t71
    <<: *owner-repo

version: 2.1

orbs:
  go: palantir/go@0.0.18
  godel: palantir/godel@0.0.18

all-tags-filter: &all-tags-filter
  filters:
    tags:
      only: /.*/

workflows:
  version: 2
  verify-test-dist-publish:
    jobs:
      - godel/verify:
          name: verify
          <<: *executor
          <<: *all-tags-filter
      - godel/test:
          name: test
          <<: *executor
          <<: *all-tags-filter
      - godel/dist:
          name: dist
          <<: *executor
          <<: *all-tags-filter
