// This file was generated by Conjure and should not be manually edited.

package api

import (
	"context"

	"github.com/palantir/conjure-go-runtime/v2/conjure-go-client/httpclient"
)

type HealthSyncServiceClient interface {
	// Collect metrics from Garmin Connect for the given activity.
	Collect(ctx context.Context, requestArg ActivityRequest) error
}

type healthSyncServiceClient struct {
	client httpclient.Client
}

func NewHealthSyncServiceClient(client httpclient.Client) HealthSyncServiceClient {
	return &healthSyncServiceClient{client: client}
}

func (c *healthSyncServiceClient) Collect(ctx context.Context, requestArg ActivityRequest) error {
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("Collect"))
	requestParams = append(requestParams, httpclient.WithRequestMethod("POST"))
	requestParams = append(requestParams, httpclient.WithPathf("/api/collect"))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	resp, err := c.client.Do(ctx, requestParams...)
	if err != nil {
		return err
	}
	_ = resp
	return nil
}
