products:
  health-sync-server:
    build:
      output-dir: build
      version-var: github.com/najork/health-sync-server/cmd.Version
      main-pkg: .
      environment:
        CGO_ENABLED: "0"
      os-archs:
        - os: darwin
          arch: amd64
        - os: linux
          arch: amd64
    dist:
      output-dir: build
      disters:
        os-arch-bin:
          type: os-arch-bin
          config:
            os-archs:
            - os: linux
              arch: amd64
            - os: darwin
              arch: amd64
    publish: {}
    docker:
      docker-builders:
        health-sync-server:
          type: default
          context-dir: ./docker
          dockerfile-path: Dockerfile
          input-products-dir: inputs
          tag-templates:
            release: "health-sync-server:{{Version}}"
            snapshot: "health-sync-server:snapshot"
product-defaults:
  publish:
    group-id: org.najork.health-sync-server
